### PR TITLE
minor fixes

### PR DESCRIPTION
**Pull request by vcordes79**
allow focus change via tab key
set correct initial value

### CODE REVIEW

**Comment by kolesnikovav** [comment]
@vcordes79  Thank you.

**Comment by vcordes79** [comment]
You're welcome. I think you can close Issues #17 and #29 . When will you publish the new code to npm?

**Comment by kolesnikovav** [comment]
I'm going bump new version tomorow or today.

**Comment by kolesnikovav** [comment]
I've publish new version with your changes.

Value watcher in VNumericInput has been rewritten to made this property reactive

**Pull request merged**
